version = 1

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[transformers]]
name = "black"

DEEPSOURCE_DSN=https://63c3e4e8f2944f75996d1498e8bbaeb3@app.deepsource.com
