version: "3.8"
services:
  base: &base-spec
    build:
      context: .
      dockerfile: Dockerfile
      args:
        image: mcr.microsoft.com/devcontainers/base:jammy # 기본 이미지로 사용할 이미지 지정
    platform: linux/amd64
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE

  main:
    <<: *base-spec
    volumes:
      - .:/netfuzz

  ubuntu22.04:
    <<: *base-spec
    build:
      context: .
      dockerfile: Dockerfile
      args:
        image: ubuntu:22.04 # Ubuntu 22.04 이미지를 사용할 때
