name: Docker build
on:
  pull_request:
    paths:
      - '**'
      - '!mkdocs.yml'
      - '!docs/**'
      - '!*.md'

jobs:
  docker:
    strategy:
      fail-fast: false
      matrix:
        images: [ubuntu22.04]

    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v4

    - name: Cache for docker images
      uses: docker/setup-buildx-action@v2
      
    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-docker-${{ matrix.images }}-v1
        restore-keys: |
          ${{ runner.os }}-docker-

    - name: Docker Build ${{ matrix.images }}
      run: |
        docker buildx build --cache-from=type=local,src=/tmp/.buildx-cache --cache-to=type=local,dest=/tmp/.buildx-cache --tag ${{ matrix.images }} .

    - name: Test on ${{ matrix.images }}
      run: docker compose run ${{ matrix.images }} ./tests.sh